#### 对比Numpy和Pytorch模块，进行思维转换

In [1]:
import torch
import numpy as np

In [8]:
print(torch.cuda.is_available())

True


#### Pytorch有自己的数据格式：张量Tensor

In [27]:
np_data=np.arange(6).reshape((2,3))
torch_data=torch.tensor(np_data)
print(np_data)
print(torch_data)

[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)


In [28]:
print(type(np_data))
print(type(torch_data))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


#### Pytorch的数据转换成Numpy的数据

In [29]:
tensor2numpy=torch_data.numpy()
print(tensor2numpy)
type(tensor2numpy)

[[0 1 2]
 [3 4 5]]


numpy.ndarray

#### 将整型数组转换成浮点型

In [30]:
data=[-1,-2,1,2]
tensor=torch.FloatTensor(data)
print(tensor)
type(tensor)

tensor([-1., -2.,  1.,  2.])


torch.Tensor

#### API文档查阅：https://pytorch.org/docs/stable/index.html

In [31]:
#求绝对值
print(np.abs(data))
print(torch.abs(tensor))

[1 2 1 2]
tensor([1., 2., 1., 2.])


In [32]:
#求sin函数值,均非常类似
print(np.sin(data))
print(torch.sin(tensor))

[-0.84147098 -0.90929743  0.84147098  0.90929743]
tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [33]:
#求平均值
print(np.mean(data))
print(torch.mean(tensor))

0.0
tensor(0.)


In [34]:
#矩阵运算,相乘
data=[[1,2],[3,4]]
tensor=torch.tensor(data)
print(np.matmul(data,data))
print(torch.mm(tensor,tensor))

[[ 7 10]
 [15 22]]
tensor([[ 7, 10],
        [15, 22]])


In [47]:
#对于.dot（）函数的应用并不一致
data=[[1,2],[3,4]]
data=np.array(data)
print(data.dot(data))
print(torch.dot(torch.tensor([1,2]),torch.tensor([3,4])))

[[ 7 10]
 [15 22]]
tensor(11)
