### Layers : Fundamental blocks of Neural Network

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable


In [2]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10,out_features=5,bias=True) 
myLayer(inp)

tensor([[ 0.7157, -0.2291,  0.1168, -0.6819, -0.1470]], grad_fn=<ThAddmmBackward>)

In [3]:
myLayer.weight

Parameter containing:
tensor([[-0.1565, -0.1731,  0.1545, -0.1311, -0.1017,  0.2231, -0.3051,  0.1107,
          0.1592,  0.3046],
        [-0.0888, -0.1380,  0.2126,  0.1781,  0.1708, -0.1193,  0.1617,  0.2165,
         -0.1241,  0.0072],
        [-0.2937, -0.0193, -0.1485,  0.1974, -0.1007, -0.0991, -0.0097,  0.2388,
          0.2164, -0.1397],
        [-0.0980, -0.1791, -0.2804, -0.1245, -0.0631, -0.3112,  0.1475, -0.1500,
          0.2107, -0.1182],
        [-0.0263,  0.2945, -0.1771,  0.2613,  0.0650, -0.2104, -0.1896,  0.0330,
         -0.1437, -0.1885]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
tensor([-0.0027,  0.2344,  0.0274,  0.2295,  0.2901], requires_grad=True)

### Stacking Linear layers

In [5]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[ 0.7593, -0.6816]], grad_fn=<ThAddmmBackward>)

### PyTorch Non-linear Activations

In [6]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)

tensor([[1., 2., 0., 0.]])

In [7]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### Neural Network 

In [8]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

### Loss

In [9]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

In [10]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [11]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### Optimizer

In [ ]:
# for demo
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr = 0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()